### ISSUE TITLE
Quadra fails to start an experiment when used in a barely initialized git repository

### ISSUE THREAD

**Issue by lorenzomammana** [orobix/quadra#26]
### What happened?

Right now we try to store the current commit inside the experiment hyperparameters for reproducibility, this causes an error when working inside of a git repository that doesn't contain any commit.

### What version are you seeing the problem on?

1.0.*

### How to reproduce the bug?

Create a folder, run git init and try to run quadra inside that folder

### Relevant log output

```shell
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error executing job with overrides: ['experiment=base/segmentation/unet_3d.yaml', 'datamodule.data_path=remote/microcard/microcard_patch/images', 'datamodule.target_path=remote/microcard/microcard_patch/masks']
Traceback (most recent call last):
  File "/opt/conda/envs/graffa/lib/python3.9/site-packages/quadra/main.py", line 41, in main
    task.execute()
  File "/opt/conda/envs/graffa/lib/python3.9/site-packages/quadra/tasks/base.py", line 273, in execute
    self.train()
  File "/opt/conda/envs/graffa/lib/python3.9/site-packages/quadra/tasks/base.py", line 231, in train
    utils.log_hyperparameters(
  File "/opt/conda/envs/graffa/lib/python3.9/site-packages/lightning_utilities/core/rank_zero.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/graffa/lib/python3.9/site-packages/quadra/utils/utils.py", line 183, in log_hyperparameters
    hparams["git/commit"] = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("ascii").strip()
  File "/opt/conda/envs/graffa/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/graffa/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
```

**Comment by lorenzomammana** [comment]
Closed in #46
